[package]
name = "crab-lang"
version = "0.1.0"
edition = "2021"

[lib]
name = "crab_lib"
path = "crab_lib/lib.rs"


[dependencies]
codespan-reporting = "0.11.1"
str_indices = "0.4.0"

[profile.release]
debug = true
